version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CORS_ALLOWED_ORIGIN=http://localhost:3000
    networks:
      - chess-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev -- -H 0.0.0.0
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - chess-network

networks:
  chess-network:
    driver: bridge
